networks:
  default:
    driver: bridge
    name: roboshop

services:
  mongodb:
    image: raghuvamsi/mongo:v1
    container_name: mongo
  catalogue:
    image: raghuvamsi/catalogue:v1
    container_name: catalogue
    depends_on:
    - mongodb
  redis:
    image: raghuvamsi/redis:v1
    container_name: redis
  user:
    image: raghuvamsi/user:v1
    container_name: user
    depends_on:
    - redis
    - mongodb
  cart:
    image: raghuvamsi/cart:v1
    container_name: cart
    depends_on:
    - redis
    - catalogue
  mysql:
    image: raghuvamsi/mysql:v1
    container_name: mysql
  shipping:
    image: raghuvamsi/shipping:v1
    container_name: shipping
    depends_on:
    - cart
    - mysql
